BASE_CSS = """
* { box-sizing:border-box; } html,body { margin:0; width:100%; height:100%; overflow:hidden; }
body { background:#020b14; color:#e9fbff; font-family:Segoe UI,Arial,sans-serif; }
.shell { width:100%; height:100%; padding:18px; background:radial-gradient(circle at center,#082333,#01070d 75%); }
.panel { background:rgba(5,19,29,.88); border:1px solid #00dff5; padding:14px; box-shadow:0 0 14px #00dff522; }
h1 { margin:0; font-size:20px; letter-spacing:3px; color:#fff; } h2 { color:#00eaff; font-size:11px; letter-spacing:2px; margin:0 0 12px; }
.value { color:#57ffb8; font-size:24px; font-weight:bold; } .muted { color:#91b9c9; font-size:11px; }
.grid { display:grid; gap:12px; height:100%; } .header { display:flex; justify-content:space-between; align-items:center; height:64px; margin-bottom:12px; }
.badge { color:#57ffb8; font-size:11px; } .log { color:#91b9c9; font:12px monospace; line-height:1.8; }
"""


def page(title, body, extra=""):
    return f'''<!doctype html><html><head><meta charset="utf-8"><title>{title}</title><style>{BASE_CSS}{extra}</style></head><body>{body}<script>window.jarvisUpdate=function(d){{var e=document.getElementById('udp');if(e)e.textContent=d.connected?'UDP LIVE · '+d.packets+' packets':'UDP WAITING';}};</script></body></html>'''

DASHBOARDS = {
    "Normal / Dev": page("JARVIS Normal", '''<main class="shell"><header class="panel header"><h1>JARVIS // NEURAL CORE</h1><span class="badge">● SYSTEM ONLINE</span></header><section class="grid" style="grid-template-columns:1fr 2fr 1fr"><div class="panel"><h2>SYSTEM DIAGNOSTICS</h2><div class="log">&gt; AI KERNEL ONLINE<br>&gt; LOCAL MEMORY READY<br>&gt; SECURITY GUARD ACTIVE<br>&gt; AUTO-FIX STANDBY</div></div><div class="panel"><h2>ACTIVITY STREAM</h2><div class="log">&gt; Awaiting instruction...<br>&gt; Workspace synchronized<br>&gt; All systems nominal</div></div><div class="panel"><h2>PERFORMANCE</h2><div class="value">READY</div><p class="muted">Local-first execution</p></div></section></main>'''),
    "F1 Engineer": page("JARVIS F1", '''<main class="shell"><header class="panel header"><h1>F1 PIT WALL // RACE ENGINEER</h1><span id="udp" class="badge">UDP WAITING</span></header><section class="grid" style="grid-template-columns:280px 1fr 280px;grid-template-rows:1fr 130px"><div class="panel"><h2>RACE STATUS</h2><div class="value">P1</div><p class="muted">LAP 16 / 67 · DELTA -0.342s</p><h2>TYRES</h2><div class="log">FL 104°C · 1.2 bar<br>FR 105°C · 1.1 bar<br>RL 113°C · 1.2 bar<br>RR 115°C · 1.3 bar</div></div><div class="panel" style="display:grid;place-items:center"><div style="width:320px;height:320px;border:2px dashed #ff7b00;border-radius:50%;display:grid;place-items:center;box-shadow:0 0 35px #ff7b0066"><div style="width:180px;height:180px;border:2px solid #00eaff;border-radius:50%;display:grid;place-items:center;color:#ffb454;font-weight:bold">LIVE</div></div></div><div class="panel"><h2>ENGINE / HYBRID</h2><div class="log">RPM <b>11,850</b><br>TEMP <b style="color:#ff6b6b">112°C</b><br>ERS <b style="color:#57ffb8">78%</b><br>FUEL <b>+1.2 LAPS</b></div><h2>RADIO</h2><div class="log">BOX THIS LAP<br>MEDIUM TYRES</div></div><div class="panel" style="grid-column:1/4;display:flex;justify-content:space-around;align-items:center;color:#ffb454;font-weight:bold"><span>RPM 11,850</span><span>ERS 78%</span><span>PIT WINDOW T25–28</span><span>UDP 20777</span></div></section></main>'''),
    "Discrete": page("JARVIS Discrete", '''<main class="shell" style="display:grid;place-items:center"><div class="panel" style="width:420px"><h1>JARVIS</h1><p class="badge">● DISCRETE MODE</p><p class="muted">Background monitoring active.</p><p id="udp" class="muted">UDP WAITING</p></div></main>'''),
    "Background": page("JARVIS Background", '''<main class="shell" style="display:grid;place-items:center"><div class="panel" style="width:520px"><h1>BACKGROUND WORKER</h1><p class="badge">● RUNNING</p><div class="log">&gt; Monitoring tasks<br>&gt; Automatic validation enabled<br>&gt; Reports will appear when complete</div></div></main>'''),
    "Architect": page("JARVIS Architect", '''<main class="shell"><header class="panel header"><h1>ARCHITECT // SYSTEM DESIGN</h1><span class="badge">ADR READY</span></header><section class="grid" style="grid-template-columns:1fr 1fr"><div class="panel"><h2>COMPONENTS</h2><div class="log">UI → Controller → Telemetry adapter<br>Controller → Provider router<br>Config → Local encrypted boundary</div></div><div class="panel"><h2>DECISIONS</h2><div class="log">ADR-001: Native desktop shell<br>ADR-002: UDP listener isolated<br>ADR-003: Local-first configuration</div></div></section></main>'''),
    "Crisis Diagnostic": page("JARVIS Crisis", '''<main class="shell" style="display:grid;place-items:center"><div class="panel" style="width:700px"><h1>CRISIS DIAGNOSTIC</h1><p class="badge">● INCIDENT RESPONSE READY</p><div class="log">Collecting logs...<br>Network listener isolated.<br>No destructive action will be executed automatically.</div></div></main>'''),
    "Executive": page("JARVIS Executive", '''<main class="shell"><header class="panel header"><h1>EXECUTIVE BRIEFING</h1><span class="badge">● READY</span></header><section class="grid" style="grid-template-columns:1fr 1fr"><div class="panel"><h2>PRIORITIES</h2><div class="log">01 · Review active projects<br>02 · Validate pending tasks<br>03 · Prepare next action</div></div><div class="panel"><h2>STATUS</h2><div class="value">NOMINAL</div></div></section></main>''')
}
